plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.143'
    id 'idea'
    id 'org.jetbrains.kotlin.jvm'  version '2.0.21'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets {
    datagen {
        java.srcDir 'src/datagen/java'


        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
        compileClasspath += sourceSets.main.output

        runtimeClasspath += sourceSets.main.output
    }
}
sourceSets.main.resources {
    srcDir('src/generated/resources')


    exclude("**/*.bbmodel") // BlockBench project files
    exclude("src/generated/**/.cache") // datagen cache files
}


repositories {
    mavenLocal()

    maven {
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {

            data()
            sourceSet = sourceSets.datagen
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath() ,
            '--existing-mod', 'mekanism','--existing-mod', 'ae2'


        }

        // applies to all the run configs above
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        sourceSet(sourceSets.datagen)
        }
    }
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime

    datagenImplementation.extendsFrom implementation
}

dependencies {
    //Mekanism and official addons
    implementation "curse.maven:mekanism-268560:7904058"
    implementation "curse.maven:mekanism-generators-268566:7904061"
    implementation "curse.maven:mekanism-additions-345425:7904060"
    implementation "curse.maven:mekanism-tools-268567:7904062"

    //MekAL
    implementation "curse.maven:mekanism-addon-library-1607060:8744214"

    //MWGR
    implementation "curse.maven:mekanism-water-generator-rebuild-1396471:8492800"

    //Addons of Mekanism
    implementation "curse.maven:mekanism-extras-1026040:7921191"
    implementation "curse.maven:evolved-mekanism-1230085:7599592"
    implementation "curse.maven:iglee-library-541199:7000755"

    //AE2 and its addons
    implementation "curse.maven:ae2addonlib-1366135:7222312"
    implementation "curse.maven:guideme-1173950:7127444"
    implementation "curse.maven:geckolib-388172:7707149"
    implementation "curse.maven:glodium-957920:5821676"
    implementation "curse.maven:applied-energistics-2-223794:7027323"
    implementation "curse.maven:applied-mekanistics-574300:7096962"
    implementation "curse.maven:advancedae-1084104:7849217"
    implementation "curse.maven:ex-pattern-provider-892005:8025439"
    implementation "curse.maven:mega-cells-622112:7952621"
    implementation "curse.maven:ae2-lightning-tech-1527395:8575479"
    implementation "curse.maven:thunderbolt-core-1631756:8592271"

    //JEI
    implementation "curse.maven:jei-238222:7391682"
    implementation "curse.maven:ae2-jei-integration-1074338:7727898"

    //Datagen only
    datagenImplementation "curse.maven:mekanism-elements-1103224:8531162"
    datagenImplementation "curse.maven:applied-flux-965012:8204513"
    datagenImplementation "curse.maven:mekanism-more-machine-1275257:7919872"
    
    datagenImplementation "curse.maven:mystical-agriculture-246640:8344249"
    datagenImplementation "curse.maven:cucumber-272335:8035802"


}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
